apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-spring-cloud.fullname" . }}
  labels:
    {{- include "helm-spring-cloud.labels" . | nindent 4 }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "helm-spring-cloud.selectorLabels" . | nindent 4 }}
